# Generated by Django 3.2.4 on 2021-06-15 15:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0004_auto_20200704_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlacklistIP',
            new_name='BlockedIP',
        ),
        migrations.RenameModel(
            old_name='BlacklistUserAgent',
            new_name='BlockedUserAgent',
        ),
        migrations.AlterModelOptions(
            name='blockedip',
            options={'verbose_name': 'BlockList IP', 'verbose_name_plural': 'BlockList IPs'},
        ),
        migrations.AlterModelOptions(
            name='blockeduseragent',
            options={'verbose_name': 'Blocklisted User Agent', 'verbose_name_plural': 'Blocklisted User Agents'},
        ),
        migrations.AlterField(
            model_name='hit',
            name='ip',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterModelTable(
            name='blockedip',
            table=None,
        ),
        migrations.AlterModelTable(
            name='blockeduseragent',
            table=None,
        ),
    ]
